### PR TITLE
Add CODE_OF_CONDUCT.md 😎

### PR DESCRIPTION
**Pull request by kutyel**
This is @sindresorhus's default one, I think it is awesome! ❤️

### CODE REVIEW

**Comment by sindresorhus** [comment]
If you didn't already use it, you can easily generate a Code of Conduct with [`conduct`](https://github.com/sindresorhus/conduct) ;)

**Comment by kutyel** [comment]
@sindresorhus yup, I have it on global so I just ran the command 😛

**Comment by kutyel** [comment]
Wow I didn't notice that one! haha done 👍

**Comment by alexjoverm** [comment]
I think @sindresorhus conduct library adds it automagically :)

**Pull request merged**
