### PR TITLE
Create CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by AndreaGot**

### CODE REVIEW

**Comment by alexjoverm** [comment]
Hi @AndreaGot! Thanks for the effort and the PR!

I must say is not exactly as I had in mind. I see it a bit too generic, I wanted something more specific. Let's say something like:

```markdown
We're really glad you're reading this, because we need volunteer developers to help this project come to fruition. 👏

## Instructions

These steps will guide you through contributing to this project:

 - Fork the repo
 - Clone it and install dependencies

```bash
git clone https://github.com/YOUR-USERNAME/typescript-library-starter
npm install
```

Keep in mind that after running `npm install` the git repo is reset. So a good way to cope with this is to have a copy of the folder to push the changes, and the other to try them.

Make and commit your changes. Make sure the commands `npm run build` and `npm run test:prod` are working.

Finally send a [GitHub Pull Request](https://github.com/alexjoverm/typescript-library-starter/pull/new/master) with a clear list of what you've done (read more about [pull requests](http://help.github.com/pull-requests/)). Make sure all of your commits are atomic (one feature per commit).
```

Is that ok for you? Any improvement over this is more than welcome!

**Comment by AndreaGot** [comment]
Which points do you want me to cover? I suppose you want something more than the one you wrote :D 

I'll be on a business trip during next week, so I won't be able to fulfill this task shortly, I'm afraid..

**Comment by alexjoverm** [comment]
Not at all. Basically if you copy/paste what I wrote up there, that'd be good enough ;)

Just wanted to make it easy for you, since writing a contributing.md file is very specific in each repo.

**Comment by alexjoverm** [comment]
The code of conduct I'd prefer it in a separate file, but that should be part of a different PR, not this one.

**Comment by alexjoverm** [comment]
There we go! Thanks!

**Pull request merged**
