### PR TITLE
Update package.json with jest option

### PR DESCRIPTION
**Pull request by YagoLopez**
Add --notify option to Jest to show test results in a pop-up window (AFAIK working in Win10)
It can be useful when test are running in a background window.

### CODE REVIEW

**Comment by YagoLopez** [comment]
Hello @alexjoverm 

Do you know what is going on with this PR? I only added a couple of options in scripts section in package.json. It should not affect builds, but reading Travis logs i can't understand what is wrong and think it could be useful to have jest notifications. Thanks.

**Comment by mattmazzola** [comment]
Your PR description says add `--notify` but all your changes add `--jest`

I don't understand the point of calling `jest --jest`. I don't see it in their CLI options:
https://facebook.github.io/jest/docs/en/cli.html#notify

**Comment by mattmazzola** [comment]
Also, from the Travis logs I'm suspecting you didn't break the build, it was already broken.  The previous commits to master which are updating package.json without updating package-lock.json which cause them to be out of sync.  This means the `npm ci` command will fail because it's designed to ensure package-lock.json is source of truth, where as `npm install` uses package.json as source of truth and will update package-lock.json.

For instance the logs say:
```
npm ERR! Invalid: lock file's @types/node@9.4.7 does not satisfy @types/node@^10.0.3
```
and there was PR #209 which only updated package.json and causes the issue.

> Merge pull request #209 from alexjoverm/greenkeeper/@types/node-10.0.3
https://github.com/alexjoverm/typescript-library-starter/commit/cae1aac9091102084f071eaf4266ed7cd444a5e5

It looks like he fixed it but manually updating package-lock.json here:
https://github.com/alexjoverm/typescript-library-starter/commit/0e9e3831c1360b6eab73c83fbc4da36f7a44311e

So if you re-base your changes and re-run build I suspect it would work.

**Comment by alexjoverm** [comment]
Sorry, I think tests are running as expected already. Build was broken as @mattmazzola said but was fixed

**Comment by YagoLopez** [comment]
Excuse me, It was an error. I made the changes quickly online. You are right, the added option should be `jest --notify`. That must be the reason why package.json and package-lock.json are out of sync. Do you think is it worth I try to make fork in my pc and send a new PR?

**Comment by mattmazzola** [comment]
> That must be the reason why package.json and package-lock.json are out of sync

No, command flags have nothing to do with package versions.

Do you think is it worth I try to make fork in my pc and send a new PR?

I don't think it's clear that this should be a default.  I assume there are people who would not want the notification distracting them.

**Comment by YagoLopez** [comment]
I understand. BTW to be precise I was refering to files out of sync due to a pull request made online, not that the cause was a command flag, keep in mind English is not my first language, and congratulations for the repository. It has been very useful for me.

**Pull request closed without merging**
