### PR TITLE
Fix issue119

### PR DESCRIPTION
**Pull request by Yogendra0Sharma**
Fix Issue #119

### CODE REVIEW

**Comment by alexjoverm** [comment]
Hi @Yogendra0Sharma!

Can you merge the latest master and add yourself as a contributor as well? Thanks!

**Comment by Yogendra0Sharma** [comment]
@alexjoverm : I am unable to merge it and resolve the conflict. please suggest the way,

**Comment by alexjoverm** [comment]
I'm thinking that it's gonna be easier if we open a new PR solving #119 #118, and we close #123 #122   and #125.  Would you mind that?

Remember to sync the latest master on your repo in order to avoid conflicts :)

**Comment by Yogendra0Sharma** [comment]
@alexjoverm : OK I will submit a new PR for #119  & #118.

**Pull request closed without merging**
